#pragma config(Motor,  port2,           frontRightMotor, tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port3,           frontLeftMotor, tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port4,           backRightMotor, tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port5,           backLeftMotor, tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port6,           rightFlywheel, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           leftFlywheel,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           intakeMotor,   tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!



int launcherSpeed = 127;
bool launcherRunning = false;

void runLauncher(int speed){
	if(speed > 127)
		speed = 127;
	if(speed < 127)
		speed = -127;
	motor[rightFlywheel] = speed;
	motor[leftFlywheel] = speed;
}

task motor_control{
	if((vexRT[Btn5U] == 0) == (vexRT[Btn6U] == 0)){
		motor[frontLeftMotor] = vexRT[Ch2];
		motor[backRightMotor] = vexRT[Ch2];
		motor[frontRightMotor] = vexRT[Ch3];
		motor[backLeftMotor] = vexRT[Ch3];
		} else if(vexRT[Btn5U] == 1) {
		motor[frontLeftMotor] = 127;
		motor[backRightMotor] = 127;
		motor[frontRightMotor] = 127;
		motor[backLeftMotor] = 127;
		wait1Msec(40);
		} else{
		motor[frontLeftMotor] = -127;
		motor[backRightMotor] = -127;
		motor[frontRightMotor] = -127;
		motor[backLeftMotor] = -127;
		wait1Msec(40);
	}
	wait1Msec(10);
}

task launcher_toggle_listener(){
	while(true){
		if(vexRT[btn8D] == 1  && !launcherRunning)
			runLauncher(launcherSpeed);
		if(vexRT[btn8D] == 1 && launcherRunning)
			runLauncher(0);
		while(vexRT[btn8D] == 1)
			wait1Msec(50);
		wait1Msec(50);
	}
}

task launcher_speed_control(){
	while(true){
		if(vexRT[Btn8L] == 1 && vexRT[Btn8R] == 0){
			launcherSpeed -= 12.7;
			while(vexRT[Btn8L] == 1)
				wait1Msec(20);
			} else if(vexRT[Btn8L] == 0 && vexRT[Btn8R] == 1){
			launcherSpeed += 12.7;
			while(vexRT[Btn8R] == 1)
				wait1Msec(20);
		}
		wait1Msec(50);
	}
}

task intake_control(){
	while(true){
		if(vexRT[Btn7U] == 1)
			motor[intakeMotor] = 127;
		else if(vexRT[Btn7D] == 1)
			motor[intakeMotor] = -127;
		else
			motor[intakeMotor] = 0;
		wait1Msec(50);
	}
}





/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...

}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	// .....................................................................................
	// Insert user code here.
	// .....................................................................................
	runLauncher(127);
	launcherRunning = true;
	wait(3);
	motor[intakeMotor] = 50;
	wait(10);
	motor[intakeMotor] = 0;
	runLauncher(0);
	launcherRunning = false;
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{

	startTask(launcher_toggle_listener);
	startTask(launcher_speed_control);
	startTask(motor_control);
	startTask(intake_control);
	// User control code here, inside the loop

	while (true)
	{
		// This is the main execution loop for the user control program. Each time through the loop
		// your program should update motor + servo values based on feedback from the joysticks.

		// .....................................................................................
		// Insert user code here. This is where you use the joystick values to update your motors, etc.
		// .....................................................................................
		wait(1);
	}
}
