#pragma config(Motor,  port2,           frontMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           backMotor,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//motors


bool tank = false;
float magnitude;
float direction;

task drivemode_toggle_listener(){
	while(true){
		if(vexRT[Btn8D] == 1){
			tank = !tank;
		}
		while(vexRT[Btn8D] == 1){
			wait1Msec(5);
		}
		wait1Msec(5);
	}
}

task main(){
	startTask(drivemode_toggle_listener);
	while(true){
		if(tank){
			motor[frontMotor] = vexRT[Ch2];
			motor[backMotor] = vexRT[Ch3];
		}
		if(!tank){
			if(vexRT[Ch1] == 0){
				if(vexRT[Ch2] >= 0)
					direction = PI/4;
				else
					direction = 5 * PI/4;
				} else if(vexRT[Ch1]<0) {
				direction = atan(vexRT[Ch2] / vexRT[Ch1] + PI/4);
				} else{
				direction = atan(vexRT[Ch2] / vexRT[Ch1]);
			}
			magnitude = sqrt(pow(vexRT[Ch1] * cos(direction), 2) + pow (vexRT[Ch2] * sin(direction), 2));
			motor[frontMotor] = magnitude * cos(direction - PI/4);
			motor[backMotor] = magnitude * sin(direction - PI/4);
		}
		wait1Msec(10);
	}
}
